apiVersion: v1
kind: PersistentVolume
metadata:
  labels:
    app: app
    type: local
  name: postgresdb-persistent-volume
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  hostPath:
    path: /data/db
  storageClassName: azure-disk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: azure-disk
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nc-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: azure-disk